### PR TITLE
Basic backwards compatibility

### LINKED ISSUE #143: how to make backwards compatible changes ?
The naiive thing doesn't seem to work:

```
package main

import (
	"fmt"
	"github.com/tendermint/go-amino"
)

type V1 struct {
	String string `json:"string"`
}

type V2 struct {
	String string `json:"string"`
	Int    int    `json:"int"`
}

func main() {
	cdc := amino.NewCodec()

	v2 := V2{String: "hi"}
	bz, _ := cdc.MarshalBinaryBare(v2)
	var v1 V1
	err := cdc.UnmarshalBinaryBare(bz, &v1)
	fmt.Println(err)
	fmt.Println(v1)

}
```

Returns:

```
Invalid typ3 byte
{hi}
```

So it does unmarshal whatever it can, but it also returns an error.

If the order of String and Int are reversed in V2, it just fails outright.

### LINKED ISSUE #145: Error field type descriptions
It would be good to nice better error messages, such as the type the prefix bytes represent.
Here is a message I got recently:
```
Expected field type 496E74657266616365, got 3842797465
```
kind of hard to gather much information from this apart from something is wrong with the marshalling

### PR DESCRIPTION
**Pull request by liamsi**
To achieve basic backwards compatibility, we continue reading the passed buffer even if all fields were already read. We only check if what follows is valid amino encoding.

resolves #143 

this also includes changes of #153 which 
resolves #145

### CODE REVIEW

File: binary-decode.go [hunk 1]
```diff
@@ -695,18 +696,158 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
 
 		// Read "StructTerm".
 		// NOTE: In the future, we'll need to break out of a loop
-		// when encoutering an StructTerm typ3 byte.
-		var typ = Typ3(0x00)
+		// when encountering an StructTerm typ3 byte.
+
+		var typ Typ3
```
Comment (jaekwon) [inline binary-decode.go]: This and the comments above belong below the for-loop

File: binary-decode.go [hunk 2]
```diff
@@ -695,18 +696,158 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
...
+		// we have read all, or do we? consume the rest
+		for len(bz) > 2 && bz[0]&0xF8 != 0 && Typ3(bz[0]) != Typ3_StructTerm {
```
Comment (jaekwon) [inline binary-decode.go]: I think we just want a for loop with no condition here, and below in `decodeFieldNumberAndTyp3(bz)` break (without sliding) if typ3 is Typ3_StructTerm.  

Then, line 716~723 below is unneeded, as the unconditional for-loop will return an error if after sliding bz is insufficient in length.  Ergo no need for len(bz) > 2 in the if-condition.

File: binary-decode.go [hunk 3]
```diff
@@ -695,18 +696,158 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
...
+			fnum, typ3, _n, _ := decodeFieldNumberAndTyp3(bz)
```
Comment (jaekwon) [inline binary-decode.go]: But we'd have to check the error instead of assigning to _.  
In general it's a bad idea to ignore errors, usually it's wrong.

File: binary-decode.go [hunk 4]
```diff
@@ -695,18 +696,158 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
...
+			if slide(&bz, &n, _n) && err != nil {
```
Comment (jaekwon) [inline binary-decode.go]: This err is the wrong err to check, as it wasn't assigned from `decodeFieldNumberAndTyp3`.

File: binary-decode.go [hunk 5]
```diff
@@ -695,18 +696,158 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
...
+				return
+			}
+			if fnum > uint32(len(info.Fields)) {
```
Comment (jaekwon) [inline binary-decode.go]: This conditional should rather be a sanity check, that fnum > `greatest field number seen`.  Instead of len(info.Fields) (which isn't forward-compatible once we support custom field tag numbers), above line 651 we should keep track of `var lastFieldNum` which we keep incrementing in both for loops (651 and 703), and we should return an error from either for-loop if each newly encountered field doesn't have a greater field number than `lastFieldNum`.

As is, this conditional block will just be ignored if fnum doesn't increment, but lets be more restrictive in our decoding.

File: binary-decode.go [hunk 6]
```diff
@@ -695,18 +696,158 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
...
 		if typ != Typ3_StructTerm {
-			err = errors.New(fmt.Sprintf("Expected StructTerm typ3 byte, got %X", typ))
+			err = errors.New(fmt.Sprintf("expected StructTerm typ3 byte, got %v", typ))
+			return
+		}
+	}
+	return
+}
+
+// read everything without doing anything with it
```
Comment (jaekwon) [inline binary-decode.go]: Full sentence, so capital r and ends with a period.

**Review by jaekwon — CHANGES_REQUESTED** [review]
Left comments in the file diff view

File: binary-decode.go [hunk 7]
```diff
@@ -677,12 +678,12 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
 			// So in the future, this may not match,
 			// so we will need to remove this sanity check.
 			if field.BinFieldNum != fieldNum {
-				err = errors.New(fmt.Sprintf("Expected field number %v, got %v", field.BinFieldNum, fieldNum))
+				err = errors.New(fmt.Sprintf("expected field number %v, got %v", field.BinFieldNum, fieldNum))
```
Comment (rigelrozanski) [inline binary-decode.go]: use `fmt.Errorf` throughout instead of `errors.New(fmt.Sprintf(`

File: binary-decode.go [hunk 8]
```diff
@@ -695,18 +696,158 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
...
+		panic("should not happen")
+
+	}
+
+	slide(&bz, &n, _n)
+	return
+}
+
+func consumeStruct(bz []byte) (n int, err error) {
+	var _n, typ = int(0), Typ3(0x00)
```
Comment (rigelrozanski) [inline binary-decode.go:806]: what's this `_n` variable I keep seeing - as an outsider I'm left in the dark also typically don't want to use underscores in names, but depending on what `_n` is it may be appropriate

File: binary-decode.go [hunk 9]
```diff
@@ -695,18 +696,158 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
...
+		if slide(&bz, &n, _n) && err != nil {
+			return
+		}
+		var term bool
+		term, _n, err = consumeAny(typ, bz)
+		if slide(&bz, &n, _n) && err != nil {
 			return
 		}
+		if term {
+			break FOR_LOOP
```
Comment (rigelrozanski) [inline binary-decode.go]: line jumps makes for spaghetti code, avoid at all costs - in this situation you can just use `break` 
```golang
if term {
	break
}
```
and then delete the like with `FOR_LOOP:`

File: binary-decode.go (hunk 8 above)
Comment (liamsi) [reply binary-decode.go:806]: for the sake of consistency this follows: https://github.com/tendermint/go-amino/blob/ecf42f8907e063f630fcce7605c61252db93c355/reflect.go#L42-L51

I'm happy to change this but would do this everywhere in the code (and not only here) in a separate issue.

File: binary-decode.go (hunk 9 above)
Comment (liamsi) [reply binary-decode.go]: done (replace `break` with `return` though, b/c that's what happens after the for loop)

File: binary-decode.go (hunk 7 above)
Comment (liamsi) [reply binary-decode.go]: done; with all other occurrences in this file

File: binary-decode.go (hunk 8 above)
Comment (rigelrozanski) [reply binary-decode.go:806]: yup sounds good - I'm the outsider here hehe

File: binary-decode.go (hunk 3 above)
Comment (liamsi) [reply binary-decode.go]: Good catch! The whole purpose of this line is to catch potential errors ...

File: binary-decode.go (hunk 5 above)
Comment (liamsi) [reply binary-decode.go]: Perfect 💯Thanks a lot for the thorough review and the suggestions!

File: binary-decode.go (hunk 4 above)
Comment (liamsi) [reply binary-decode.go]: fixed

File: binary-decode.go (hunk 1 above)
Comment (liamsi) [reply binary-decode.go]: following 
> Then, line 716~723 below is unneeded

I deleted the part outside the for-loop and with it this comment(s).

**Comment by liamsi** [comment]
Thanks @jaekwon and @rigelrozanski for the thorough review. All should be addressed now. 

PTAL.

File: binary-decode.go (hunk 2 above)
Comment (liamsi) [reply binary-decode.go]: I added a small test to see if this works.

**Comment by rigelrozanski** [comment]
my comments are addressed 👍

File: binary-decode.go [hunk 10]
```diff
@@ -630,9 +631,12 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
 	}
 	_n := 0 // nolint: ineffassign
 
+	// Keep incrementing the last fieldnum. Later, when we support custom fieldtag numbers, we need to store the last
```
Comment (jaekwon) [inline binary-decode.go]: should be declared in the case statement in the switch statement?

File: binary-decode.go [hunk 11]
```diff
@@ -648,6 +652,7 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
 	default:
 		// Read each field.
 		for _, field := range info.Fields {
+			lastFieldNum++
```
Comment (jaekwon) [inline binary-decode.go]: It's semantically awkward to increment it here in the beginning... Instead I'd increment at the end of the for-loop.

File: binary-decode.go [hunk 12]
```diff
@@ -670,19 +675,25 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
 				// Probably a StructTerm.
 				break
 			}
+			if fieldNum < lastFieldNum {
```
Comment (jaekwon) [inline binary-decode.go]: like, semantically it should be `if fieldNum <= lastFieldNum`, because it shouldn't be lastFieldNum either.

File: binary-decode.go [hunk 13]
```diff
@@ -693,20 +704,163 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
...
-		// Read "StructTerm".
-		// NOTE: In the future, we'll need to break out of a loop
-		// when encoutering an StructTerm typ3 byte.
-		var typ = Typ3(0x00)
-		typ, _n, err = decodeTyp3(bz)
+		var _n, fnum = 0, uint32(0)
+		var typ3 Typ3
+		// we have read all, or do we? consume the rest
+		for {
+			lastFieldNum++
```
Comment (jaekwon) [inline binary-decode.go]: This is especially awkward here because...

File: binary-decode.go [hunk 14]
```diff
@@ -693,20 +704,163 @@ func (cdc *Codec) decodeReflectBinaryStruct(bz []byte, info *TypeInfo, rv reflec
...
+
+			fnum, typ3, _n, err = decodeFieldNumberAndTyp3(bz)
+			if typ3 == Typ3_StructTerm {
+				break
+			}
+			if slide(&bz, &n, _n) && err != nil {
+				return
+			}
+			if fnum < lastFieldNum {
```
Comment (jaekwon) [inline binary-decode.go]: ... it should be `if fnum <= lastFieldNum { ... } else { lastFieldNum = fnum }`.  The `lastFieldNum++` above is incorrect.

**Review by jaekwon — CHANGES_REQUESTED** [review]
Added more comments in file change view

File: binary-decode.go (hunk 14 above)
Comment (liamsi) [reply binary-decode.go]: Then, in the 1st check above (in the 1st for-loop) should also not just increment (`lastFieldNum++`) but set to `lastFieldNum = fnum` instead. Or is there any reason why this should be different only here? 

If we increment like before (in the beginning of the loop and stick to `<`) it is indeed semantically awkward (totally agree) but not incorrect. At least, I tried constructing a test where decoding fails but couldn't (only by manually modifying the bytes to have fieldnums which are not just start with zero and then "last + 1"; in other words with "gaps" in between the numbering). 

Always setting `lastFieldNum = fnum` will also work if we add manual field numbering support. Incrementing only works because the numbering is implicitly given by the field order.

File: binary-decode.go (hunk 11 above)
Comment (liamsi) [reply binary-decode.go]: See [below](https://github.com/tendermint/go-amino/pull/155/files#r191466725). I don't increment now but set `lastFieldNum = fieldnum` instead (not at the end but right after the check)

File: binary-decode.go (hunk 10 above)
Comment (liamsi) [reply binary-decode.go]: Thx, done.
