### PR TITLE
Fix zero time decoding

### LINKED ISSUE #189: Fix failing tests on circleci before release v0.11.0
Decoding time sometimes fails because the 1st field might be skipped as with #178

I have a fix for this lined up, will push later.

https://circleci.com/gh/tendermint/go-amino/413?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### PR DESCRIPTION
**Pull request by liamsi**
fix for changes in #178 (introduced a decoding bug for zero values)

resolves #189 

PTAL @xla @jaekwon

### CODE REVIEW

File: amino.go [hunk 1]
```diff
@@ -87,6 +88,9 @@ const (
 	//Typ3_Interface  = Typ3(7)
 )
 
+// we use this time to init. a zero value (opposed to reflect.Zero which gives time.Time{} / 01-01-01 00:00:00)
+var zeroTime, _ = time.Parse("2006-01-02 15:04:05 +0000 UTC", "1970-01-01 00:00:00 +0000 UTC")
```
Comment (xla) [inline amino.go]: It's not very likely but ignoring the error is not advisable. There are multiple ways to do this, one is to use a global and then have an init function which panics if the parse fails, or have a little wrapper like `mustParse` which panics in case of an error. The latter is desirable as use of `init` needs to be considered and initialisation order needs to be kept in mind.

Those strings would make for great constants.

File: decoder.go [hunk 2]
```diff
@@ -198,54 +198,23 @@ func DecodeFloat64(bz []byte) (f float64, n int, err error) {
...
-		}
+	sec, n, err = decodeSeconds(&bz)
+	if err != nil {
+		return
 	}
-	// Actually read the Int32.
-	var nsec = int32(0)
-	nsec, _n, err = DecodeInt32(bz)
-	if slide(&bz, &n, _n) && err != nil {
+	nsec, err := decodeNanos(&bz, &n)
```
Comment (xla) [inline decoder.go:213]: The implicit return values make it hard to reason about what is returned at what point. Here for example is the returned `err` set correctly? If possible we should avoid them, good reasons to use implicit returns is for access in `defer`s.

File: decoder.go [hunk 3]
```diff
@@ -258,6 +227,52 @@ func DecodeTime(bz []byte) (t time.Time, n int, err error) {
...
+		if slide(bz, &n, _n) && err != nil {
+			return 0, n, err
+		} else {
+			return sec, n, err
+		}
+	} else if fieldNum == 2 && typ == Typ3_4Byte {
+		// skip: do not slide, no error, will read again
+		return 0, n, nil
+	} else {
+		return 0, n, fmt.Errorf("expected field number 1 <8Bytes> or field number 2 <4Bytes> , got %v", fieldNum)
```
Comment (xla) [inline decoder.go:251]: Is there a general error strategy for amino? While totally out of scope of this PR, errors should be properly constructed (sentinels, or types) to give control to the caller. Esp. important with low-level libs.

File: decoder.go [hunk 4]
```diff
@@ -258,6 +227,52 @@ func DecodeTime(bz []byte) (t time.Time, n int, err error) {
...
+	}
+}
+
+func decodeNanos(bz *[]byte, n *int) (int32, error) {
+	// Optionally decode field number 2 and Typ3 (4Byte).
+	//var fieldNum, typ, _n = uint32(0), Typ3(0x00), int(0)
```
Comment (xla) [inline decoder.go]: Maybe wec an rewrite this comment to show the layout in the byte slice, as an example check [this section](https://github.com/tendermint/go-amino#prefix-bytes-to-identify-the-concrete-type) from the README.

File: encoder.go [hunk 5]
```diff
@@ -117,7 +117,6 @@ func EncodeFloat64(w io.Writer, f float64) (err error) {
 func EncodeTime(w io.Writer, t time.Time) (err error) {
 	var s = t.Unix()
 	var ns = int32(t.Nanosecond()) // this int64 -> int32 is safe.
-
```
Comment (xla) [inline encoder.go]: Any particular reason to remove the whitespace here?

File: time2_test.go [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+
+import (
+	"testing"
+	"time"
+
+	"github.com/stretchr/testify/assert"
+)
+
+func TestDecodeTime(t *testing.T) {
+
```
Comment (xla) [inline time2_test.go]: Unnecessary newline.

File: time2_test.go [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+	type T struct {
```
Comment (xla) [inline time2_test.go]: No need to have this uppercase, would be nice to give it a more descriptive title.

**Review by xla — APPROVED** [review]
:+1: :octocat: :shipit: :dango: 

LGTM, just some style and consistency comments.

File: decoder.go (hunk 2 above)
Comment (liamsi) [reply decoder.go:213]: Yes, returns the correct err. But I agree with with the implicit returns. I did not want to change the public method here for the sake of consistency: all methods in this file have named return values/implicit returns.

File: decoder.go (hunk 3 above)
Comment (liamsi) [reply decoder.go:251]: Agreed! But out of scope for this PR as you said (https://github.com/tendermint/go-amino/issues/191)

File: encoder.go (hunk 5 above)
Comment (liamsi) [reply encoder.go]: nope... I think, I've added some debugging code which I deleted later (and with it that innocent line). Can reintroduce that.

File: decoder.go (hunk 4 above)
Comment (liamsi) [reply decoder.go]: Thanks! I just forgot to delete this comment. I don't think there should be a general comment about how the byteslice will look here. It's very general (typ3AndFieldnum | actualBytesOfField) where typ3AndFieldnum is encoded via: (field_number << 3) | typ3 and not special. 
I'll delete the comment. A more public facing documentation should explain how time is encoded though.

File: amino.go (hunk 1 above)
Comment (liamsi) [reply amino.go]: Thanks! Very good suggestions 👍

File: time2_test.go (hunk 6 above)
Comment (liamsi) [reply time2_test.go]: adressed

File: time2_test.go (hunk 7 above)
Comment (liamsi) [reply time2_test.go]: adressed

**Comment by liamsi** [comment]
Thanks for the timely and thorough review @xla!
If the fuzzer doesn't find any issue I'll merge today (cc @jaekwon)

File: decoder.go (hunk 2 above)
Comment (xla) [reply decoder.go:213]: Understood, changing those won't affect anything on the caller side tho.
